# This is workflow name
name: hello workflow

# runs on a trigger, whenever changes is pushed to branch
on:
  push:
     branches: [main]
     
# these are jobs inside the workflow
jobs: 

  # this is the name of the job
  greet:

    # this is github runner
    runs-on:  ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"

      - name: say hello to username
        run: echo "Hello $USER"
  details:
   runs-on: ubuntu-latest
   steps:
    - name: show what is the version of python,docker, etc
      run: docker --version && python --version
    
